Document: gamecredits
Title: Debian gamecredits Manual
Author: <insert document author here>
Abstract: This manual describes what gamecredits is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gamecredits/gamecredits.sgml.gz

Format: postscript
Files: /usr/share/doc/gamecredits/gamecredits.ps.gz

Format: text
Files: /usr/share/doc/gamecredits/gamecredits.text.gz

Format: HTML
Index: /usr/share/doc/gamecredits/html/index.html
Files: /usr/share/doc/gamecredits/html/*.html
